# Generated by Django 4.2.24 on 2025-09-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
