# Generated by Django 4.2.24 on 2025-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=5)),
                ('porte', models.CharField(max_length=7)),
                ('castrado', models.CharField(max_length=3)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('vacinado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PetPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=5)),
                ('localidade', models.CharField(max_length=200)),
                ('caracteristicas', models.TextField()),
            ],
        ),
    ]
