# Generated by Django 4.2.24 on 2025-09-22 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadocao',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets_adocao', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petperdido',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets_perdidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
