# Generated by Django 4.2.24 on 2025-09-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_petadocao_user_petperdido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadocao',
            name='foto',
            field=models.ImageField(default=1, upload_to='images/adocao/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petperdido',
            name='foto',
            field=models.ImageField(default=1, upload_to='images/perdidos/'),
            preserve_default=False,
        ),
    ]
