# Generated by Django 4.2.24 on 2025-09-23 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adocao', '0003_petadocao_foto_petperdido_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadocao',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_adocao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petperdido',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_perdido', to=settings.AUTH_USER_MODEL),
        ),
    ]
